### ISSUE TITLE
Deprecate kubernetes below 1.18

### ISSUE THREAD

**Issue by viceice** [renovatebot/helm-charts#137]
I think we should stop testing kubernetes versions below 1.18 to save ci build time.

Is anybody using renovate on such old version

**Comment by JamieMagee** [comment]
I originally based the versions used in tests on the supported versions by AWS, Azure, and GCP. Here are the lists of supported versions:

- [AWS](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html)
- [Azure](https://docs.microsoft.com/en-us/azure/aks/supported-kubernetes-versions#aks-kubernetes-release-calendar)
- [GCP](https://cloud.google.com/kubernetes-engine/docs/release-notes)

Currently the lowest supported versions are:

<table>
<tr>
	<td>Cloud</td>
	<td>Version</td>
<tr>
	<td>AWS</td>
	<td>1.16</td>
<tr>
	<td>Azure</td>
	<td>1.18</td>
<tr>
	<td>GCP</td>
	<td>1.18</td>
</table>

And highest supported versions:

<table>
<tr>
	<td>Cloud</td>
	<td>Version</td>
<tr>
	<td>AWS</td>
	<td>1.20</td>
<tr>
	<td>Azure</td>
	<td>1.20 (1.21 in preview)</td>
<tr>
	<td>GCP</td>
	<td>1.20 (1.21 in preview)</td>
</table>

**Comment by viceice** [comment]
So continue to support 1.16

**Comment by JamieMagee** [comment]
I think we could probably drop support for <1.18, as AWS is the only cloud that supports it right now. Both Azure and GCP will soon drop 1.18 as well, at which point we could probably drop 1.18, and only test 1.19+

**Comment by viceice** [comment]
So let's drop v18, when v1.22 is released? So we test latest 4 versions?

**Comment by JamieMagee** [comment]
Yeah, that sounds reasonable. That will roughly track the versions supported by the major cloud providers. Let's make a note somewhere in our docs with that.

**Comment by viceice** [comment]
> Yeah, that sounds reasonable. That will roughly track the versions supported by the major cloud providers. Let's make a note somewhere in our docs with that.

Any idea where to add the note? and what to write?

@HonkingGoose Some suggestions? 🙃

**Comment by HonkingGoose** [comment]
I'd say put a message in this repository's readme to start with. 😉 

And put a message in the source file for this page: https://docs.renovatebot.com/self-hosting/#kubernetes
