### ISSUE TITLE
Use `batch/v1` API version of `CronJob`

### ISSUE THREAD

**Issue by lindhe** [renovatebot/helm-charts#1419]
There's currently some complex logic in place to check the API versions available for `CronJob`:

https://github.com/renovatebot/helm-charts/blob/377ef241f062e29094d0e2c868bbff179fd49f87/charts/renovate/templates/cronjob.yaml#L1-L9

Since [`CronJob` has been stable since v1.21 of Kubernetes](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/), there are no longer any supported Kubernetes clusters that does not have the stable API version (`batch/v1`) of `CronJob`.

Having the logic in place sometimes cause trouble, like in #145 and when running `helm template` or (as a direct consequence) `kustomize`:

```console
$ helm template renovate renovate/renovate
Error: execution error at (renovate/templates/cronjob.yaml:8:6):

 ERROR: You must have at least batch/v1beta1 to use CronJob

Use --debug flag to render out invalid YAML

$ kustomize build --enable-helm .
Error: Error: execution error at (renovate/templates/cronjob.yaml:8:6):

 ERROR: You must have at least batch/v1beta1 to use CronJob

Use --debug flag to render out invalid YAML
: unable to run: 'helm template renovate /tmp/renovatebot/charts/renovate --namespace renovate -f /tmp/kustomize-helm-3100442017/renovate-kustomize-values.yaml' with env=[HELM_CONFIG_HOME=/tmp/kustomize-helm-3100442017/helm HELM_CACHE_HOME=/tmp/kustomize-helm-3100442017/helm/.cache HELM_DATA_HOME=/tmp/kustomize-helm-3100442017/helm/.data] (is 'helm' installed?): exit status 1
```

Therefore, I suggest we remove that logic and just use `batch/v1` without any checks.

I'm happy to create a PR for this enhancement, but I just want to check first so the contribution would be welcome.

**Comment by lindhe** [comment]
Glad to hear. Thank you for pointing out the EKS LTS being a thing.

In my PR, should I also bump the chart version number? Or is that done via a separate process?

**Comment by viceice** [comment]
> Glad to hear. Thank you for pointing out the EKS LTS being a thing.
> 
> In my PR, should I also bump the chart version number? Or is that done via a separate process?

don't bump, will be done automatically on next renovate release
