### ISSUE TITLE
Rootless DinD sidecar

### ISSUE THREAD

**Issue by viceice** [renovatebot/helm-charts#148]
We now can use the renovate slim image with DinD sidecar.

The downside is, that the DinD container needs privileged security context
https://github.com/renovatebot/helm-charts/blob/0f1da585b84fcfe9f5e39972be925ddff602d76b/charts/renovate/templates/cronjob.yaml#L132-L133

So It would be nice to use to rootless DinD version, so we don't need a priviliged container.

**Comment by kvanzuijlen** [comment]
> so we don't need a priviliged container

Not sure if this is the case, since according to the [docs](https://docs.docker.com/engine/security/rootless/#rootless-docker-in-docker), privileged is still a requirement. I still think this is an improvement though since docker itself will run as a nonroot user (user id 1000).

**Comment by viceice** [comment]
closing in favor of:
- #298
