### ISSUE TITLE
Versions for kindest/node are not updated

### ISSUE THREAD

**Issue by sebastien-prudhomme** [renovatebot/helm-charts#162]
Hi,

I take my inpsiration from the renovate configuration of this repo for my own charts and found a bug when dealing with `kindest/node` image.

The regex in `renovate.json` should not have an additionnal space just after the comment character.

Another problem is that only patch updates should be applied as you want to launch different versions on Kubernetes and not the latest one.

Can I commit a PR?

**Comment by viceice** [comment]
Sure

**Comment by viceice** [comment]
The reg x is right, the workflow config is wrong. There should always be a space like `# renovate:`

**Comment by sebastien-prudhomme** [comment]
@viceice It seems there are some inconsistencies in default renovate preset here : https://github.com/renovatebot/.github/blob/main/default.json

Is the regexManager "Update version: variables in workflows" at the end of the file also wrong?

**Comment by viceice** [comment]
Yes, as you can see, the other always have the space.
