### ISSUE TITLE
Add support for container securityContext

### ISSUE THREAD

**Issue by hazzik** [renovatebot/helm-charts#202]
We have a requirement to run all pods/container with a read-only root file system (dictated by Azure Policy) to make sure the integrity of the image. This is usually done by setting `readOnlyRootFilesystem` property to `true` on container's `securityContext`. It would be nice if the security context would be supported out of the box.

**Comment by viceice** [comment]
I think this is already supported

https://github.com/renovatebot/helm-charts/blob/d79a5a59e99558e301b0cc2d3055c03749f6b881/charts/renovate/templates/cronjob.yaml#L189-L192

**Comment by hazzik** [comment]
@viceice this is not the right security context. The property you're referencing is a [**pod** security context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod), while I was asking for a [**container** security context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container):

> This is usually done by setting `readOnlyRootFilesystem` property to true on **container's** `securityContext`. 

Here in the same file you've referenced `securityContext` is set for dnd container:

https://github.com/renovatebot/helm-charts/blob/d79a5a59e99558e301b0cc2d3055c03749f6b881/charts/renovate/templates/cronjob.yaml#L153-L154

**Comment by viceice** [comment]
feel free to send a pr

**Comment by dschunack** [comment]
@viceice Hi, is it possible to release a new version of the helm chart?

**Comment by viceice** [comment]
should normally done by next renovate update, but it seems we have some trouble on this repo, so i manually forced an update.

- https://github.com/renovatebot/renovate/issues/17483

**Comment by dschunack** [comment]
thanks
