### ISSUE TITLE
Add support for hostAliases

### ISSUE THREAD

**Issue by submac** [renovatebot/helm-charts#234]
This is rather a straightforward request to provide the support to override hostname resolution with hostAliases as described [here](https://kubernetes.io/docs/tasks/network/customize-hosts-file-for-pods/).

Example of how this could look like in cronjob:

```
...
spec:
  serviceAccountName: {{ include "renovate.serviceAccountName" . }}
  restartPolicy: {{ .Values.cronjob.jobRestartPolicy }}
{{- with .Values.hostAliases }}
  hostAliases:
    {{- toYaml . | nindent 12 }}
{{- end }}
...
```

**Comment by submac** [comment]
I prepped a quick PR #235
Let me know if anything else is missing to push this forward.

**Comment by kvanzuijlen** [comment]
@viceice I believe this issue can be closed, correct?
