### ISSUE TITLE
Add support for ttlSecondsAfterFinished

### ISSUE THREAD

**Issue by hoerup** [renovatebot/helm-charts#244]
Inorder to have k8s automatically cleanup old job runs it would be nice if the renovate helm chart supported specifying ttlSecondsAfterFinished

the field was beta in k8s 1.21 and ga in 1.23

Ref: https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/

**Comment by viceice** [comment]
needs conditional as we still support `v1.20`

**Comment by JamieMagee** [comment]
EKS just dropped support for Kubernetes `1.20` today. 

Oldest supported versions are currently:

- [EKS - 1.21](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar)
- [GKE - 1.21](https://cloud.google.com/kubernetes-engine/docs/release-schedule#schedule_for_release_channels)
- [AKS - 1.22](https://learn.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#aks-kubernetes-release-calendar)

**Comment by viceice** [comment]
ok, so we can drop v1.20 too.
