### ISSUE TITLE
chart releaser needs config update 

### ISSUE THREAD

**Issue by viceice** [renovatebot/helm-charts#260]
```
ATTENTION: Flag --charts-repo is deprecated. It does not have any effect.
Loading index file from git repository .cr-index/index.yaml
The index.yaml is read from the 'gh-pages' branch instead.
Loading index.yaml directly from the charts repository lead to problems as there is a delay between
pushing to the GitHub pages branch until things appear online.
The flag will be removed with the next major release.
```

**Comment by JamieMagee** [comment]
I don't think there is any action required on our side. We use the [helm/chart-releaser-action][1] action, and there is currently a PR[^1] open to fix this warning.

[1]: https://github.com/helm/chart-releaser-action
[^1]: https://github.com/helm/chart-releaser-action/pull/123

**Comment by viceice** [comment]
ok, let's leave this open until it's fixed upstream

**Comment by jftanner** [comment]
My PR was merged. So I expect a new version will be live shortly.
