### ISSUE TITLE
Feature request: volumeMounts for renovate-dind / option to provide `/etc/docker/daemon.json`

### ISSUE THREAD

**Issue by nobbs** [renovatebot/helm-charts#263]
Hey there, I've deployed the helm chart in our air-gapped on-prem cluster so that I can use renovate to manage helm chart dependencies against our private helm repositories and mirrors. That works fine when I use the "fat" renovate image and the option renovate config option `binarySource` to `global` (the default value `install` does not work, as there's no internet access thus tool installs failing).

I tried to use the dind option with `binarySource: "docker"` but had to scrape that as the docker daemon in the dind container tries to access `docker.io` for image pulls. As of now there is no option to modify the settings of the docker daemon inside the container, e.g. by providing a `/etc/docker/daemon.json` from a configmap or otherwise. If that would be possible, this would allow me to specify the internal docker registry mirror as a mirror to the docker daemon so that it would be able to grab the images.

Would appreciate it if this would be implemented - I could do it myself, too - just thought that a creating an issue first to get opinions would be good.

**Comment by viceice** [comment]
Do you know `dockerImagePrefix`[^1]? So you can force renovate to use images from your internal registry.

[^1]: https://docs.renovatebot.com/self-hosted-configuration/#dockerimageprefix

**Comment by viceice** [comment]
btw: the dind wouldn't help you, as renovate now uses the sidecar images and installs the tools on the fly for most managers, so needs again internet access.

**Comment by nobbs** [comment]
> Do you know `dockerImagePrefix`[^1]? So you can force renovate to use images from your internal registry.
> 
> 
> 
> [^1]: https://docs.renovatebot.com/self-hosted-configuration/#dockerimageprefix

Ah, no, must have missed that option. Thanks. That's good enough. 

Regarding your second comment, that's ... kind of unfortunate. But yeah, there's still the full image for now, too. 

Thanks, I'll close this then, as there's no need for this.

**Comment by viceice** [comment]
- #298
