### ISSUE TITLE
Remove kubernetes v1.22 (EOL on AWS at 2023-06-04)

### ISSUE THREAD

**Issue by viceice** [renovatebot/helm-charts#296]
Only AWS is still supporting that.

Azure and Google already only support v1.24+

- https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar
- https://learn.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#aks-kubernetes-release-calendar
- https://cloud.google.com/kubernetes-engine/docs/release-notes
- #137
- #178

@JamieMagee Do you think we can drop v1.22 and v1.23?

**Comment by JamieMagee** [comment]
Yes, we've done it before without making a major version change.
