### ISSUE TITLE
Chart `36.9.2` released with image `36.9.1` as the default image version

### ISSUE THREAD

**Issue by 9numbernine9** [renovatebot/helm-charts#344]
Hello! 👋 

I noticed that the newly released `36.9.2` version of the Helm chart appears to be released with `36.9.1` as the default version specified in the `values.yaml` file in the `image.tag` field. I believe this is likely an unintentional change from previous versions where the Helm chart version always matched the tag version of the `renovate/renovate` image that would be deployed.

Steps to reproduce:
- Download the released Chart tarball: https://github.com/renovatebot/helm-charts/releases/download/renovate-36.9.2/renovate-36.9.2.tgz
- Extract the contents
- Look at the `values.yaml` file and note that the `image.tag` field is `36.9.1`

**Comment by viceice** [comment]
this isn't intentional, it needs a renovate.json fix to properly group those updates

**Comment by viceice** [comment]
- #348

that PR should make a consistent release again 🎉
