### ISSUE TITLE
Helm Chart and git SSH key configuration

### ISSUE THREAD

**Issue by tjsousa** [renovatebot/helm-charts#60]
### Which Renovate are you using?

Renovate Open Source Helm Chart

### Which platform are you using?

GitLab self-hosted

### Have you checked the logs? Don't forget to include them if relevant

2020-08-31T13:07:19.47585772Z  INFO: Repository started (repository=tiago.sousa/sample-ruby-app)                                                                          │
│ 2020-08-31T13:07:19.475891312Z        "renovateVersion": "22.3.3"                                                                                                         │
│ 2020-08-31T13:07:19.800262752Z  WARN: Host error (repository=tiago.sousa/sample-ruby-app)                                                                                 │
│ 2020-08-31T13:07:19.800283853Z        "hostType": "git",                                                                                                                  │
│ 2020-08-31T13:07:19.800286844Z        "lookupName": undefined,                                                                                                            │
│ 2020-08-31T13:07:19.800289075Z        "err": {                                                                                                                            │
│ 2020-08-31T13:07:19.800291157Z          "task": {                                                                                                                         │
│ 2020-08-31T13:07:19.8002933Z            "concatStdErr": false,                                                                                                            │
│ 2020-08-31T13:07:19.800295486Z            "format": "utf-8",                                                                                                              │
│ 2020-08-31T13:07:19.800297569Z            "commands": [                                                                                                                   │
│ 2020-08-31T13:07:19.800299465Z              "clone",                                                                                                                      │
│ 2020-08-31T13:07:19.800301375Z              "--depth=2",                                                                                                                  │
│ 2020-08-31T13:07:19.80030332Z              "https://oauth2:**redacted**@**redacted-hostname**/tiago.sousa/sample-ruby-app.git",                                │
│ 2020-08-31T13:07:19.800305622Z              "."                                                                                                                           │
│ 2020-08-31T13:07:19.800307535Z            ]                                                                                                                               │
│ 2020-08-31T13:07:19.800309408Z          },                                                                                                                                │
│ 2020-08-31T13:07:19.800311308Z          "message": "Cloning into '.'...\nremote: Git access over HTTP is not allowed\nfatal: unable to access 'https://**redacted-hostname**
## What would you like to do?

I would like to be able to use an SSH key for git with the Helm chart but there doesn't seem to be a way to mount the `.ssh` directory that it expects. Any guidance on how may I be able to follow this approach while keeping the helm chart?
https://github.com/renovatebot/renovate/blob/master/docs/usage/self-hosting.md#kubernetes-for-gitlab-using-git-over-ssh

**Comment by viceice** [comment]
looks like we need some kind of configurable volumes, so we can pass secrets or config  as file

**Comment by gmelillo** [comment]
@viceice I've the need of using this feature, would be fine to propose a PR to introduce the possibility of providing `ssh. config`, `ssh. id_rsa`, `ssh. id_rsa_pub` or a predefined config map name?

**Comment by viceice** [comment]
sure, but make sure it's optional

**Comment by gmelillo** [comment]
Something like `ssh.enabled` defaulted to `false` to not break the backwards compatibility may work?

**Comment by viceice** [comment]
Yes, any solution which don't break is ok. 

We should use helm best practises for volumes. I'm not a helm expert, so can't really help.

**Comment by JamieMagee** [comment]
@tjsousa Did #85 close this issue for you?
