### ISSUE TITLE
Missing New Chart Versions

### ISSUE THREAD

**Issue by cliedeman** [renovatebot/helm-charts#71]
```bash
helm repo add renovate https://docs.renovatebot.com/helm-charts
helm repo update
helm search repo renovate
```
Returns 

```bash
renovate/renovate       23.66.0         23.66.0         Universal dependency update tool that fits into...
```

Edit: this seems to be due to ci failures. But I am still curious where the older charts are

**Comment by viceice** [comment]
Looks like a renovate preset issue

**Comment by viceice** [comment]
Or a workflow problem

**Comment by cliedeman** [comment]
```
Error: Chart.yaml file is missing
Failed to package chart in /home/runner/work/helm-charts/helm-charts (Chart.yaml file is missing)
```

That duplicate helm-charts folder looks suspicious

**Comment by viceice** [comment]
@JamieMagee looks like the release workflow has an issue here

https://github.com/renovatebot/helm-charts/blob/4d89a35734df6f1cbe7c56bc5fa69f694410e743/.github/workflows/release.yaml#L21

**Comment by viceice** [comment]
Fixed

**Comment by cliedeman** [comment]
@viceice thanks

**Comment by JamieMagee** [comment]
@viceice Thanks for the fix! At the time I put this together, `chart-releaser-action` didn't have a stable release.

**Comment by viceice** [comment]
I know, checked the releases, so they must have done some breakings on master branch 🙃

Fixed that on mobile 😅
