### ISSUE TITLE
Openshift (Kubernetes v1.25.12+26bab08): `You must have at least batch/v1beta1 to use CronJob`

### ISSUE THREAD

**Issue by kmarilleau** [renovatebot/helm-charts#720]
Openshift version: `4.12.33`
Kubernetes version: `v1.25.12+26bab08`
Renovate Bot Helm Chart version: `37.65.2`

Hi,

I've got the following Error during deployment on Openshift:
`You must have at least batch/v1beta1 to use CronJob`

I've been trying the following code manually and it seems to return `batch/v1/CronJob` which is the good API version of Batch CronJob:
```bash
$ if [[ "$(./semver2.sh "${KUBERNETES_VERSION#v}" 1.21.0)" -ge 0 ]]; then
  echo "batch/v1/CronJob"
else
  echo "batch/v1beta1/CronJob"
fi
```

I don't understand why the Helm Chart is not returning the good API version.

**Comment by viceice** [comment]
maybe your kubernetes has some cronjob disabled?

here is how we check for support:
https://github.com/renovatebot/helm-charts/blob/main/charts/renovate/templates/cronjob.yaml#L1

how are you installing the Helm chart?

**Comment by kmarilleau** [comment]
I close this issue, the issue comes from our pipelines.
it works now and we don't need to specidy the apiVersion for cronjob at all.
