### ISSUE TITLE
Add optional DIND sidecar

### ISSUE THREAD

**Issue by JamieMagee** [renovatebot/helm-charts#91]
Add optional configuration to include a Docker DIND sidecar in the renovate pod. This allowed [`binarySource`](https://docs.renovatebot.com/self-hosted-configuration/#binarysource) to be set to `docker`

See https://github.com/renovatebot/renovate/discussions/8169#discussioncomment-254419

**Comment by viceice** [comment]
How to kill dind sidecar when renovate finished: https://github.com/kubernetes/kubernetes/issues/25908#issuecomment-308569672

**Comment by viceice** [comment]
I think this will help too: renovatebot/renovate#9087
