### ISSUE TITLE
Update chart to v2 (Helm v3)

### ISSUE THREAD

**Issue by viceice** [renovatebot/helm-charts#97]
Helm v2 is obsolete, so we should update chart to v2 metadata to only support Helm v3

ref: https://helm.sh/docs/topics/v2_v3_migration/

**Comment by JamieMagee** [comment]
Do you have any guidance on what needs to be done?

**Comment by viceice** [comment]
@JamieMagee I think we only need to update `apiVersion` to `v2`, see my pr 🙃
