### ISSUE TITLE
Return code not correct when using preCommand and postCommand options

### ISSUE THREAD

**Issue by deutschj** [renovatebot/helm-charts#974]
When using the `preCommand` and `postCommand` values, the Kubernetes CronJob always uses the return code of the `postCommand`, no matter if the `renovate` exits with RC 0 or not. This way, if the `renovate` command fails, it still looks like the CronJob completed successfully. This makes it impossible to tell if Renovate has really failed, without taking a look at the logs.

This happens because the `args` field in the cronjob.yaml template is declared as a multiline string. By concatenating the `preCommand`, `renovate` and `postCommand` values inline with `&&` instead, this issue could be fixed and the Kubernetes CronJob would use the return code of the `renovate` command instead. Therefore if renovate fails, the CronJob will display status `Error` instead of `Completed`. 
I could submit a PR suggesting this solution.

**Comment by viceice** [comment]
concatening with `&&` isn't a solution there can be more in those pre an d post commands. so a solution would be more complex

**Comment by danielhass** [comment]
@viceice makes sense. What would you think about prefixing the templated pre/post commands with a `set -e` in order to fail directly on every non-zero exit code?

**Comment by viceice** [comment]
sounds good

**Comment by deutschj** [comment]
@viceice I created pull request #1023 to add the `set -e` option.
